[project]
name = "mlbscores"
version = "0.1.0"
description = "mlbscores is a Python script that reads publicly available JSON data from mlb.com and prints out up-to-date scores, reduced box scores, and league standings."
requires-python = ">=3.11"
dependencies = [
]

authors = [
    {name = "Seamus Riordan",email = ""}
    {name = "Kevin Bowen",email = "kevin.bowen@gmail.com"}
]
maintainers = [
    { name = "Kevin Bowen", email = "kevin.bowen@gmail.com" },
]
license = "CC0-1.0"
readme = "README.md"

classifiers = [
    # https://pypi.org/pypi?:action=list_classifiers
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Games/Entertainment",
    "Topic :: Utilities",
]

[project.urls]
Homepage = "https://github.com/kevinbowen777/mlbscores.git"
Changelog = "https://github.com/kevinbowen777/mlbscores/CHANGELOG"
Repository = "https://github.com/kevinbowen777/mlbscores.git"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
